"""initial_schema

Revision ID: 77ed6f4336a8
Revises: 
Create Date: 2026-06-10 05:07:24.224606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ed6f4336a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('ruc', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('logo_path', sa.Text(), nullable=True),
    sa.Column('eslogan', sa.Text(), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('trial_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firma_id', sa.String(length=36), nullable=False),
    sa.Column('ruc', sa.String(length=20), nullable=False),
    sa.Column('razon_social', sa.Text(), nullable=False),
    sa.Column('nombre_fantasia', sa.Text(), nullable=True),
    sa.Column('actividad_principal', sa.Text(), nullable=True),
    sa.Column('regimen', sa.String(length=20), nullable=False),
    sa.Column('tipo_contribuyente', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('email_dnit', sa.String(length=100), nullable=True),
    sa.Column('clave_marangatu', sa.Text(), nullable=True),
    sa.Column('estado_dnit', sa.String(length=20), nullable=False),
    sa.Column('fecha_inscripcion', sa.String(length=10), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['firma_id'], ['firmas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firma_id', 'ruc')
    )
    op.create_table('credenciales_marangatu',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firma_id', sa.String(length=36), nullable=False),
    sa.Column('cliente_ruc', sa.String(length=20), nullable=False),
    sa.Column('usuario_dnit_enc', sa.Text(), nullable=False),
    sa.Column('clave_dnit_enc', sa.Text(), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['firmas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firma_id', 'cliente_ruc')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firma_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('avatar_path', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['firmas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auditorias',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firma_id', sa.String(length=36), nullable=False),
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.Column('periodo_desde', sa.String(length=7), nullable=False),
    sa.Column('periodo_hasta', sa.String(length=7), nullable=False),
    sa.Column('tipo_encargo', sa.String(length=50), nullable=False),
    sa.Column('impuestos', sa.Text(), nullable=False),
    sa.Column('materialidad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('auditor', sa.String(length=200), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['firma_id'], ['firmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_trail',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firma_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('auditoria_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('accion', sa.Text(), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('datos_json', sa.Text(), nullable=True),
    sa.Column('resultado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditorias.id'], ),
    sa.ForeignKeyConstraint(['firma_id'], ['firmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cedulas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firma_id', sa.String(length=36), nullable=False),
    sa.Column('auditoria_id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('datos_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditorias.id'], ),
    sa.ForeignKeyConstraint(['firma_id'], ['firmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('declaraciones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firma_id', sa.String(length=36), nullable=False),
    sa.Column('auditoria_id', sa.String(length=36), nullable=True),
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.Column('formulario', sa.String(length=10), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('fecha_presentacion', sa.String(length=19), nullable=False),
    sa.Column('estado_declaracion', sa.String(length=20), nullable=False),
    sa.Column('nro_rectificativa', sa.Integer(), nullable=False),
    sa.Column('datos_json', sa.Text(), nullable=False),
    sa.Column('archivo_pdf', sa.Text(), nullable=True),
    sa.Column('descargado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditorias.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['firma_id'], ['firmas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firma_id', 'cliente_id', 'formulario', 'periodo', 'nro_rectificativa')
    )
    with op.batch_alter_table('declaraciones', schema=None) as batch_op:
        batch_op.create_index('idx_declaraciones_firma_periodo', ['firma_id', 'periodo'], unique=False)

    op.create_table('declaraciones_juradas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firma_id', sa.String(length=36), nullable=False),
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.Column('auditoria_id', sa.String(length=36), nullable=True),
    sa.Column('formulario', sa.String(length=10), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('numero_orden', sa.String(length=20), nullable=True),
    sa.Column('total_debito', sa.BigInteger(), nullable=False),
    sa.Column('total_credito', sa.BigInteger(), nullable=False),
    sa.Column('saldo_a_favor_contrib', sa.BigInteger(), nullable=False),
    sa.Column('saldo_a_favor_fisco', sa.BigInteger(), nullable=False),
    sa.Column('campos_json', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditorias.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['firma_id'], ['firmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hallazgos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firma_id', sa.String(length=36), nullable=False),
    sa.Column('auditoria_id', sa.String(length=36), nullable=False),
    sa.Column('impuesto', sa.String(length=20), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('tipo_hallazgo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('descripcion_tecnica', sa.Text(), nullable=True),
    sa.Column('articulo_legal', sa.Text(), nullable=False),
    sa.Column('base_ajuste', sa.Integer(), nullable=False),
    sa.Column('impuesto_omitido', sa.Integer(), nullable=False),
    sa.Column('multa_estimada', sa.Integer(), nullable=False),
    sa.Column('intereses_estimados', sa.Integer(), nullable=False),
    sa.Column('total_contingencia', sa.Integer(), nullable=False),
    sa.Column('nivel_riesgo', sa.String(length=10), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas_auditor', sa.Text(), nullable=True),
    sa.Column('evidencias', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.String(length=50), nullable=False),
    sa.Column('sugerencia_ai', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditorias.id'], ),
    sa.ForeignKeyConstraint(['firma_id'], ['firmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hallazgos', schema=None) as batch_op:
        batch_op.create_index('idx_hallazgos_firma_riesgo', ['firma_id', 'nivel_riesgo', 'estado'], unique=False)

    op.create_table('hechauka',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firma_id', sa.String(length=36), nullable=False),
    sa.Column('auditoria_id', sa.String(length=36), nullable=True),
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('ruc_informante', sa.String(length=20), nullable=False),
    sa.Column('nombre_informante', sa.Text(), nullable=True),
    sa.Column('tipo_operacion', sa.String(length=30), nullable=False),
    sa.Column('nro_comprobante', sa.String(length=30), nullable=True),
    sa.Column('fecha_comprobante', sa.String(length=10), nullable=True),
    sa.Column('monto_operacion', sa.Integer(), nullable=False),
    sa.Column('iva_operacion', sa.Integer(), nullable=False),
    sa.Column('retencion_iva', sa.Integer(), nullable=False),
    sa.Column('retencion_ire', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditorias.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['firma_id'], ['firmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hechauka', schema=None) as batch_op:
        batch_op.create_index('idx_hechauka_firma_periodo', ['firma_id', 'periodo'], unique=False)

    op.create_table('informes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firma_id', sa.String(length=36), nullable=False),
    sa.Column('auditoria_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('archivo_docx', sa.Text(), nullable=True),
    sa.Column('archivo_pdf', sa.Text(), nullable=True),
    sa.Column('generado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditorias.id'], ),
    sa.ForeignKeyConstraint(['firma_id'], ['firmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rg90',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firma_id', sa.String(length=36), nullable=False),
    sa.Column('auditoria_id', sa.String(length=36), nullable=True),
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('ruc_contraparte', sa.String(length=20), nullable=False),
    sa.Column('nombre_contraparte', sa.Text(), nullable=True),
    sa.Column('timbrado', sa.String(length=20), nullable=True),
    sa.Column('establecimiento', sa.String(length=5), nullable=True),
    sa.Column('punto_expedicion', sa.String(length=5), nullable=True),
    sa.Column('nro_comprobante', sa.String(length=20), nullable=False),
    sa.Column('cdc', sa.String(length=44), nullable=True),
    sa.Column('tipo_comprobante', sa.String(length=5), nullable=True),
    sa.Column('fecha_emision', sa.String(length=10), nullable=False),
    sa.Column('base_gravada_10', sa.Integer(), nullable=False),
    sa.Column('base_gravada_5', sa.Integer(), nullable=False),
    sa.Column('monto_exento', sa.Integer(), nullable=False),
    sa.Column('iva_10', sa.Integer(), nullable=False),
    sa.Column('iva_5', sa.Integer(), nullable=False),
    sa.Column('iva_total', sa.Integer(), nullable=False),
    sa.Column('total_comprobante', sa.Integer(), nullable=False),
    sa.Column('cdc_valido', sa.Boolean(), nullable=True),
    sa.Column('ruc_activo', sa.Boolean(), nullable=True),
    sa.Column('en_sifen', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fuente_archivo', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditorias.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['firma_id'], ['firmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rg90', schema=None) as batch_op:
        batch_op.create_index('idx_rg90_cdc', ['cdc'], unique=False)
        batch_op.create_index('idx_rg90_firma_periodo', ['firma_id', 'periodo'], unique=False)

    op.create_table('sifen_comprobantes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firma_id', sa.String(length=36), nullable=False),
    sa.Column('auditoria_id', sa.String(length=36), nullable=True),
    sa.Column('cdc', sa.String(length=44), nullable=False),
    sa.Column('tipo_de', sa.String(length=5), nullable=False),
    sa.Column('ruc_emisor', sa.String(length=20), nullable=False),
    sa.Column('nombre_emisor', sa.Text(), nullable=True),
    sa.Column('ruc_receptor', sa.String(length=20), nullable=True),
    sa.Column('nombre_receptor', sa.Text(), nullable=True),
    sa.Column('timbrado', sa.String(length=20), nullable=True),
    sa.Column('establecimiento', sa.String(length=5), nullable=True),
    sa.Column('punto_expedicion', sa.String(length=5), nullable=True),
    sa.Column('nro_comprobante', sa.String(length=20), nullable=True),
    sa.Column('fecha_emision', sa.String(length=25), nullable=False),
    sa.Column('base_gravada_10', sa.Integer(), nullable=False),
    sa.Column('base_gravada_5', sa.Integer(), nullable=False),
    sa.Column('monto_exento', sa.Integer(), nullable=False),
    sa.Column('iva_total', sa.Integer(), nullable=False),
    sa.Column('total_comprobante', sa.Integer(), nullable=False),
    sa.Column('estado_sifen', sa.String(length=20), nullable=False),
    sa.Column('consultado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditorias.id'], ),
    sa.ForeignKeyConstraint(['firma_id'], ['firmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sifen_comprobantes', schema=None) as batch_op:
        batch_op.create_index('idx_sifen_firma_cdc', ['firma_id', 'cdc'], unique=False)

    op.create_table('tareas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firma_id', sa.String(length=36), nullable=False),
    sa.Column('auditoria_id', sa.String(length=36), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.Column('fecha_completado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditorias.id'], ),
    sa.ForeignKeyConstraint(['firma_id'], ['firmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tareas')
    with op.batch_alter_table('sifen_comprobantes', schema=None) as batch_op:
        batch_op.drop_index('idx_sifen_firma_cdc')

    op.drop_table('sifen_comprobantes')
    with op.batch_alter_table('rg90', schema=None) as batch_op:
        batch_op.drop_index('idx_rg90_firma_periodo')
        batch_op.drop_index('idx_rg90_cdc')

    op.drop_table('rg90')
    op.drop_table('informes')
    with op.batch_alter_table('hechauka', schema=None) as batch_op:
        batch_op.drop_index('idx_hechauka_firma_periodo')

    op.drop_table('hechauka')
    with op.batch_alter_table('hallazgos', schema=None) as batch_op:
        batch_op.drop_index('idx_hallazgos_firma_riesgo')

    op.drop_table('hallazgos')
    op.drop_table('declaraciones_juradas')
    with op.batch_alter_table('declaraciones', schema=None) as batch_op:
        batch_op.drop_index('idx_declaraciones_firma_periodo')

    op.drop_table('declaraciones')
    op.drop_table('cedulas')
    op.drop_table('audit_trail')
    op.drop_table('auditorias')
    op.drop_table('usuarios')
    op.drop_table('credenciales_marangatu')
    op.drop_table('clientes')
    op.drop_table('firmas')
    # ### end Alembic commands ###
